name: CI

on: [push]

jobs:
  backend_test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: download GoogleTest and run test  
      run: |
        cd backend/test
        mkdir build
        cd build
        ls
        

