name: CI

on: [push]

jobs:
  backend_test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - run: cd backend/test
    - run: mkdir build
    - run: cd build
    - run: ls
        

