name: CI

on: [push]

jobs:
  backend_test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: create build directory
      run: |
        cd backend/test
        mkdir build
    - run: ls backend/test

        

