name: BackendTest

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: backend_test
    - run: |
      cd backend/test
      mkdir build/
      cd build/
      cmake ..
      cmake --build .
      ./sudokusolver-test


